# /etc/iapm.conf

configFile  = "/etc/iapm.conf"
rootDir     = "/"
databaseDir = "/var/lib/iapm/"
cacheDir    = "/var/cache/iapm/"
logFile     = "/var/log/iapm.log"
LockFile    = "/var/lib/iapm.lock"

enableColor = True