# /etc/iapm/iapm.conf

# IAPM Configuration File

[GENERAL]
# IAPM will handle these following dictories settings like this: The finnal DataBase Dir it use is $ROOTDIR/$DBDIR instead of $DBDIR.
ROOTDIR     = "/"
DBDIR       = "/var/lib/iapm/"
CACHEDIR    = "/var/cache/iapm/"
LOGFILE     = "/var/log/iapm.log"
# These following dictories settings is not used currently, but IAPM will use in future versions.
LOCKFILE    = "/var/lib/iapm/iapm.lock"
GPGDIR      = "/etc/iapm/gpg/"

# @xxx is regarded as a package group, xxx is regarded as a package or a virtual package
# Packages in IgnoreList will not be updated, but you still can install or remove them manually.
# Packages in ImportantList is unable to be removed.
IgnoreList = []
ImportantList = ['glibc']

# Miscs
Color           = True
Verbose         = False