# /etc/iapm/repos.conf

# IAPM Repos Configuration File

[osbase]
Name            = "$OS_NAME $OS_SLOT Base"
Server          = 
GPGCheckEnable  = True
ExpireTime      = 1h

[osextra]
Name            = "$OS_NAME $OS_SLOT Extra"
Server          = 
GPGCheckEnable  = True
ExpireTime      = 1h